{"name": "test_not_equal2", "status": "skipped", "statusDetails": {"message": "XFAIL reason: \n\n_pytest.outcomes.XFailed", "trace": "self = <TestCaseFunction test_not_equal2>, testcase = <LagouTest.tests.itesting_test.ITestingTest testMethod=test_not_equal2>\nrawexcinfo = (<class 'AssertionError'>, AssertionError('1 == 1'), <traceback object at 0x00000299077ECA00>), reason = ''\n\n    def addExpectedFailure(\n        self,\n        testcase: \"unittest.TestCase\",\n        rawexcinfo: \"_SysExcInfoType\",\n        reason: str = \"\",\n    ) -> None:\n        try:\n>           xfail(str(reason))\nE           _pytest.outcomes.XFailed\n\nf:\\python39\\lib\\site-packages\\_pytest\\unittest.py:271: XFailed"}, "attachments": [{"name": "stdout", "source": "fbf40918-a92f-4ff7-bc2e-c6c395a0c83e-attachment.txt", "type": "text/plain"}], "start": 1637482571464, "stop": 1637482571465, "uuid": "5570989e-5a29-43e0-a943-ac1dbe78609e", "historyId": "85fa7730c6c2fac4501e74ca40c6d56a", "testCaseId": "6ed460fe677f5ceceec44cd2039006ba", "fullName": "tests.itesting_test.ITestingTest#test_not_equal2", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "itesting_test"}, {"name": "subSuite", "value": "ITestingTest"}, {"name": "host", "value": "TSJ-006171"}, {"name": "thread", "value": "33352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.itesting_test"}]}